---
# Source: kube-prometheus-stack/charts/grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-11.1.7
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "12.3.3"
rules: []
