---
# Source: kube-prometheus-stack/templates/grafana/configmaps-datasources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-kube-prometheus-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app: kube-prometheus-stack-grafana
    
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "81.6.1"
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-81.6.1
    release: "prometheus"
    heritage: "Helm"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: "Prometheus"
      type: prometheus
      uid: prometheus
      url: http://prometheus-kube-prometheus-prometheus.monitoring:9090/
      access: proxy
      isDefault: true
      jsonData:
        httpMethod: POST
        timeInterval: 30s
        exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
          urlDisplayLabel: 
    - name: "Alertmanager"
      type: alertmanager
      uid: alertmanager
      url: http://prometheus-kube-prometheus-alertmanager.monitoring:9093/
      access: proxy
      jsonData:
        handleGrafanaManagedAlerts: false
        implementation: prometheus
    - access: proxy
      isDefault: false
      jsonData:
        derivedFields:
        - datasourceUid: Tempo
          matcherRegex: 'traceid[": ]*(\w+)'
          name: traceID
          url: $${__value.raw}
        - datasourceUid: Tempo
          matcherRegex: traceid
          matcherType: label
          name: traceid
          url: $${__value.raw}
      name: Loki
      orgId: 1
      type: loki
      uid: loki
      url: http://loki:3100
      version: 1
    - access: proxy
      isDefault: false
      jsonData:
        serviceMap:
          datasourceUid: prometheus
        tracesToLogsV2:
          datasourceUid: loki
          filterBySpanID: false
          filterByTraceID: true
          spanEndTimeShift: 10m
          spanStartTimeShift: -10m
          tags: []
        tracesToMetrics:
          datasourceUid: prometheus
      name: Tempo
      orgId: 1
      type: tempo
      uid: tempo
      url: http://tempo:3200
      version: 2
