---
# Source: argo-cd/templates/argocd-configs/argocd-notifications-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  labels:
    helm.sh/chart: argo-cd-9.4.1
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: "v3.3.0"
data:
  context: |
    argocdUrl: https://argocd.nasus.dev
  service.webhook.discord: |
    url: $discord-webhook-url
    headers:
    - name: Content-Type
      value: application/json
  subscriptions: |
    - recipients:
      - discord:general
      triggers:
      - on-sync-status-unknown
      - on-sync-succeeded
      - on-sync-failed
      - on-health-degraded
  template.app-health-degraded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [
              {
                "title": "⚠️ Application {{.app.metadata.name}} has degraded",
                "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "color": 16776960,
                "fields": [
                  {
                    "name": "Health Status",
                    "value": "{{.app.status.health.status}}",
                    "inline": "true"
                  },
                  {
                    "name": "Repository",
                    "value": "{{.app.spec.source.repoURL}}",
                    "inline": "false"
                  }
                  {{range $index, $c := .app.status.conditions}}
                  {{if not $index}},{{end}}
                  {{if $index}},{{end}}
                  {
                    "name": "{{$c.type}}",
                    "value": "{{$c.message}}",
                    "inline": "true"
                  }
                  {{end}}
                ]
              }
            ]
          }
  template.app-sync-failed: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [
              {
                "title": "❌ Application {{.app.metadata.name}} sync failed",
                "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "color": 16711680,
                "fields": [
                  {
                    "name": "Sync Status",
                    "value": "{{.app.status.sync.status}}",
                    "inline": "true"
                  },
                  {
                    "name": "Repository",
                    "value": "{{.app.spec.source.repoURL}}",
                    "inline": "false"
                  }
                  {{range $index, $c := .app.status.conditions}}
                  {{if not $index}},{{end}}
                  {{if $index}},{{end}}
                  {
                    "name": "{{$c.type}}",
                    "value": "{{$c.message}}",
                    "inline": "true"
                  }
                  {{end}}
                ]
              }
            ]
          }
  template.app-sync-status: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [
              {
                "title": "Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}",
                "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "color": 16776960,
                "fields": [
                  {
                    "name": "Sync Status",
                    "value": "{{.app.status.sync.status}}",
                    "inline": "true"
                  },
                  {
                    "name": "Repository",
                    "value": "{{.app.spec.source.repoURL}}",
                    "inline": "false"
                  }
                ]
              }
            ]
          }
  template.app-sync-succeeded: |
    webhook:
      discord:
        method: POST
        body: |
          {
            "embeds": [
              {
                "title": "✅ Application {{.app.metadata.name}} synced successfully",
                "url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
                "color": 65280,
                "fields": [
                  {
                    "name": "Sync Status",
                    "value": "{{.app.status.sync.status}}",
                    "inline": "true"
                  },
                  {
                    "name": "Sync Revision",
                    "value": "{{.app.status.sync.revision}}",
                    "inline": "true"
                  },
                  {
                    "name": "Repository",
                    "value": "{{.app.spec.source.repoURL}}",
                    "inline": "false"
                  }
                ]
              }
            ]
          }
  trigger.on-health-degraded: |
    - description: Application has degraded
      send:
      - app-health-degraded
      when: app.status.health.status == 'Degraded'
  trigger.on-sync-failed: |
    - description: Application syncing has failed
      send:
      - app-sync-failed
      when: app.status.operationState.phase in ['Error', 'Failed']
  trigger.on-sync-status-unknown: |
    - description: Application status is 'Unknown'
      send:
      - app-sync-status
      when: app.status.sync.status == 'Unknown'
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
