apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-traefik
  namespace: kube-system
spec:
  valuesContent: |-
    providers:
      kubernetesIngress:
        allowCrossNamespace: true
        publishedService:
          enabled: false
      kubernetesGateway:
        enabled: true
    resources:
      requests:
        cpu: 25m
        memory: 100Mi
    priorityClassName: system-cluster-critical
    ports:
      traefik:
        hostPort: 8080
    ingressRoute:
      healthcheck:
        enabled: true
        matchRule: PathPrefix(`/health`)
    experimental:
      otlpLogs: true
    metrics:
      otlp:
        enabled: true
        http:
          enabled: true
          endpoint: "http://k8s-monitoring-alloy-receiver.monitoring:4318/v1/metrics"
    tracing:
      otlp:
        enabled: true
        http:
          enabled: true
          endpoint: "http://k8s-monitoring-alloy-receiver.monitoring:4318/v1/traces"
    logs:
      access:
        enabled: true
        otlp:
          enabled: true
          http:
            enabled: true
            endpoint: "http://k8s-monitoring-alloy-receiver.monitoring:4318/v1/logs"
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=127.0.0.1"
