---
# Source: k8s-monitoring/charts/alloy-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-monitoring-alloy-operator
  namespace: monitoring
  labels:
    helm.sh/chart: alloy-operator-0.4.1
    app.kubernetes.io/name: alloy-operator
    app.kubernetes.io/instance: k8s-monitoring
    app.kubernetes.io/version: "1.5.2"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
