apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upgrade-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/Nasus20202/infra.git
    targetRevision: main
    path: kubernetes/oci/compute/cluster/applications/upgrade-controller
  destination:
    name: in-cluster
    namespace: system-upgrade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
