---
# Source: longhorn/templates/default-setting.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-setting
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn
    helm.sh/chart: longhorn-1.11.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/version: v1.11.0
data:
  default-setting.yaml: |-
    replica-soft-anti-affinity: true
    replica-auto-balance: "best-effort"
    storage-over-provisioning-percentage: "200"
    storage-minimal-available-percentage: "15"
    default-replica-count: "1"
    default-data-locality: "disabled"
    priority-class: "longhorn-critical"
    disable-revision-counter: "{\"v1\":\"true\"}"
    concurrent-automatic-engine-upgrade-per-node-limit: "1"
    guaranteed-instance-manager-cpu: "5"
