defaultSettings:
  defaultReplicaCount: "1"
  replicaSoftAntiAffinity: true
  defaultDataLocality: disabled # Options: disabled, best-effort, strict-local
  replicaAutoBalance: best-effort # disabled, least-effort, best-effort
  storageOverProvisioningPercentage: "200"
  storageMinimalAvailablePercentage: "15"
  concurrentAutomaticEngineUpgradePerNodeLimit: "1"
  guaranteedInstanceManagerCPU: "5" # 5% of 2 cores

persistence:
  defaultClassReplicaCount: 1
  reclaimPolicy: Retain
  defaultDataLocality: disabled

defaultBackupStore:
  backupTargetCredentialSecret: longhorn-backup-secret

metrics:
  serviceMonitor:
    enabled: true

# Fix for https://github.com/longhorn/longhorn/issues/12573
# TODO: Remove this override when Longhorn version >= 1.11.1 is used
image:
  longhorn:
    instanceManager:
      tag: v1.11.0-hotfix-1
